### ISSUE TITLE
Running manage.py retry_deferred crashes.

### ISSUE THREAD

**Issue by houdinihound** [SmileyChris/django-mailer-2#1]
Running the retry_deferred command causes the following traceback:

<pre>Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_manager(settings)
  File "/home/zerobug/webapps/fbs/lib/python2.6/django/core/management/__init__.py", line 362, in execute_manager
    utility.execute()
  File "/home/zerobug/webapps/fbs/lib/python2.6/django/core/management/__init__.py", line 303, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/zerobug/webapps/fbs/lib/python2.6/django/core/management/base.py", line 195, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/zerobug/webapps/fbs/lib/python2.6/django/core/management/base.py", line 222, in execute
    output = self.handle(*args, **options)
  File "/home/zerobug/webapps/fbs/lib/python2.6/django/core/management/base.py", line 351, in handle
    return self.handle_noargs(**options)
  File "/home/zerobug/webapps/fbs/fbs/../fbs/django_mailer/management/commands/retry_deferred.py", line 11, in handle_noargs
    count = models.QueuedMessage.objects.retry_deferred()
  File "/home/zerobug/webapps/fbs/fbs/django_mailer/managers.py", line 53, in retry_deferred
    self.deferred().update(**update_kwargs)
  File "/home/zerobug/webapps/fbs/lib/python2.6/django/db/models/query.py", line 413, in update
    query.add_update_values(kwargs)
  File "/home/zerobug/webapps/fbs/lib/python2.6/django/db/models/sql/subqueries.py", line 232, in add_update_values
    return self.add_update_fields(values_seq)
  File "/home/zerobug/webapps/fbs/lib/python2.6/django/db/models/sql/subqueries.py", line 245, in add_update_fields
    val = field.get_db_prep_save(val)
  File "/home/zerobug/webapps/fbs/lib/python2.6/django/db/models/fields/__init__.py", line 192, in get_db_prep_save
    return self.get_db_prep_value(value)
  File "/home/zerobug/webapps/fbs/lib/python2.6/django/db/models/fields/__init__.py", line 569, in get_db_prep_value
    return connection.ops.value_to_db_datetime(self.to_python(value))
  File "/home/zerobug/webapps/fbs/lib/python2.6/django/db/models/fields/__init__.py", line 565, in to_python
    _('Enter a valid date/time in YYYY-MM-DD HH:MM[:ss[.uuuuuu]] format.'))
django.core.exceptions.ValidationError: Enter a valid date/time in YYYY-MM-DD HH:MM[:ss[.uuuuuu]] format.
</pre>

Environment 1:
Win XP
Django 1.1.1
Python 2.6.4
PostgreSQL 8.2.7

Environment 2:
RHEL
Django 1.1.1
Python 2.6
PostgreSQL 8.2.3
Just found this - could be related: http://code.djangoproject.com/ticket/10443

Will keep digging and update with any new info.

Joe

**Comment by SmileyChris** [comment]
Why don't you try django trunk and see if it fixes your problem, since that ticket is marked fixed?

**Comment by houdinihound** [comment]
Yep, that was 1st on my to do list this morning ;)  Although it seems like that issue was fixed as of the 1.0.x series?

Anyway, ran it against latest revision (11782) - exact same error.  Only difference in the traceback is the line numbers of the error in the first 2 function calls:

<pre>
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_manager(settings)
  File "c:\django-trunk\django\core\management\__init__.py", line 439, in execute_manager
    utility.execute()
  File "c:\django-trunk\django\core\management\__init__.py", line 380, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
.
.
.
</pre>

The rest of the traceback is identical (barring the path to django version).

Also ran it with Python 2.5.4, against trunk and 1.1.1 - same results.

**Comment by SmileyChris** [comment]
It does seem like this is a database problem. If you can muck around with the database, here's a test:

My guess is that it's failing trying to update the datetimefield "deferred" on the QueuedMessage model.

From a shell, try QueuedMessage.objects.update(deferred=None)
If that fails, ensure that your deferred column of the database is nullable (the model definition says it should be).

**Comment by houdinihound** [comment]
Ok, so in the shell, QueuedMessage.objects.update(deferred=None) works (returns the # of records updated).

The db field 'deferred' is nullable and is of type "timestamp with time zone".  

Tested the above in both environments, works in both.

**Comment by houdinihound** [comment]
Resolved.  I was running an older version of django-mailer-2 (files were stamped Sep 10) and noticed the latest files have a stamp of Sep 24 and  the comment 
"Change the retry_deferred management command to output result when on 
normal verbosity level." which is why I didn't update sooner :(

Suggestion: Perhaps a version or changes file in the directory?  

Anyway, downloaded the latest version of django-mailer-2 and it now works in both environments.

I apologise for wasting your time on this and thank you for your help.

Regards,
Joe

**Comment by SmileyChris** [comment]
Glad you got it resolved. Yeah, I should start a todo. It's a common question for what the difference between this and the original mailer is.
